export const CONFIG_TECH_STACK = [
  'REACT',
  'VUEJS',
  'ANGULAR',
  'NEXTJS',
  'TYPESCRIPT',
  'NODEJS',
  'GRAPHQL',
  'MYSQL',
  'POSTGRESQL',
  'MONGODB',
  'DOCKER',
  'AWS',
  'CI/CD',
  'JENKINS',
  'KUBERNETES',
  'LARAVEL',
  'SPRING',
  'FLASK',
  'RUBY_ON_RAILS',
  'GITHUB',
  'CLOUD',
  'TENSORFLOW',
  'JAVASCRIPT',
  'HTML5',
  'CSS3',
  'SASS',
  'BOOTSTRAP',
  'TAILWINDCSS',
  'GIT',
  'WEBPACK',
  'GRUNT',
  'GULP',
  'JQUERY',
  'REACT_NATIVE',
  'NODEJS',
  'NPM',
  'YARN',
  'CLOUD_FUNCTIONS',
  'FIREBASE',
  'REDIS',
  'NGINX',
  'VAGRANT',
  'ELASTICSEARCH',
  'SOLR',
  'RABBITMQ',
  'SERVERLESS',
  'NEXUS',
  'PWA',
  'VUEX',
  'JEST',
  'MOCHA',
  'CHAI',
  'CYPRESS',
  'ESLINT',
  'PRETTIER',
  'NEXTAUTH',
  'JAVA',
  'PYTHON',
  'RUBY',
  'PHP',
  'C#',
  'C++',
  'SWIFT',
  'KOTLIN',
  'GOLANG',
  'PERL',
  'SQL',
  'COBOL',
  'OBJECTIVE_C',
  'DART',
  'MATLAB',
  'GSAP',
];

export const CONFIG_REMOTE_WORK = [
    { 
      value: 'ONSITE', 
      label: 'Pas de télétravail',
    },
    { 
      value: 'ONEDAY', 
      label: '1 jour de télétravail',
    },
    { 
      value: 'TWODAY', 
      label: '2 jours de télétravail',
    },
    { 
      value: 'THREEDAY', 
      label: '3 jours de télétravail',
    },
    { 
      value: 'FOURDAY', 
      label: '4 jours de télétravail', 
    },
    { 
      value: 'ALLDAY', 
      label: 'Télétravail complet', 
    }
  ];

export const STATUS_LABELS = {
    SENDING: 'Envoyé',
    INTERVIEW: 'Contacté',
    PENDING:  'Attente',
    REJECTED:  'Refusé',
    ACCEPTED: 'Accepté',
};